[owner]
domain = "yourdomain.co.jp"
organization = "Your Org"

[networks]
[[networks.office1]]
name = "cooperate"
ip = ["1.1.1.1", "2.2.2.2", "3.3.3.3"]

[[networks.office1]]
name = "dmz"
ip = ["1.1.1.1", "2.2.2.2", "3.3.3.3"]

[[networks.office1]]
name = "byod"
ip = ["1.1.1.1", "2.2.2.2", "3.3.3.3"]

[[networks.office1]]
name = "guest"
ip = ["1.1.1.1", "2.2.2.2", "3.3.3.3"]

[[networks.office2]]
name = "cooperate"
ip = ["1.1.1.1", "2.2.2.2", "3.3.3.3"]

[[networks.office2]]
name = "byod"
ip = ["1.1.1.1", "2.2.2.2", "3.3.3.3"]

[[networks.office2]]
name = "guest"
ip = ["1.1.1.1", "2.2.2.2", "3.3.3.3"]